name = "TRSFiles"
uuid = "d4b2941c-f37a-4ec9-8241-9a5e52a0f7fd"
authors = ["Cees-Bart Breunesse <ceeesb@gmail.com>"]
version = "0.1.3"

[deps]
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"

[compat]
Mmap = "1.11.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
